Always keep projectors window on top
mne-tools/mne-qt-browser pull request #101
Opened 2022-04-05 20:44 UTC by hoechenberger

Also minor change for code health to enforce more explicit parameter specification when creation projection dialog window.

2022-04-05 20:51 UTC, hoechenberger commented
I now added a window title too:
![Uploading Screen Shot 2022-04-05 at 22.51.21.png…]()

2022-04-05 20:57 UTC, larsoner requested changes
On linux at least, this causes the dialog to be on top *system-wide*:

![Screenshot from 2022-04-05 16-55-24](https://user-images.githubusercontent.com/2365790/161847779-39f65053-365d-4ee9-840c-defc09a130ff.png)



Maybe there is some hint here about parenting that would fix it?

https://stackoverflow.com/questions/29568038/qt-window-that-stays-on-top-of-the-application-but-not-other-windows

FYI, for me on Linux the behavior is already correct on `main`.

2022-04-05 21:03 UTC, hoechenberger commented
> On linux at least, this causes the dialog to be on top _system-wide_:

Same on macOS, but it was the only quick solution I could find so far for a non-modal window. Already a great improvement for me, though…



> https://stackoverflow.com/questions/29568038/qt-window-that-stays-on-top-of-the-application-but-not-other-windows

I read that, and we already have a parent, but this doesn't seem to suffice on macOS

> FYI, for me on Linux the behavior is already correct on `main`.

Not for me on macOS, unfortunately :(

2022-04-05 21:47 UTC, larsoner commented
Pushed a fix that works on macOS (and actually makes the title bar smaller, which is nice!), plus generalized to all `_BaseDialog`s, plus a fix for
```
TypeError: SettingsDialog.closeEvent() takes 1 positional argument but 2 were given
```
Let's see if it works on Linux, too...

2022-04-06 06:32 UTC, hoechenberger commented
Great, works for me!

Re problem with the settings dialog, I think quite some effort has been put into this in #85, so I'd suggest to revert this change here and merge #85 instead to give the author credit, no?

2022-04-06 10:49 UTC, larsoner commented
> I'd suggest to revert this change here

Done, I'll merge this PR once green now

2022-04-06 11:10 UTC, merged

2022-04-06 11:42 UTC, hoechenberger commented
Thank you, @larsoner!

PS: Can you please give me permissions to merge PRs myself here too? Otherwise I'll always have to wait for you 😅